//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuestionsApp {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Messages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Messages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("QuestionsApp.Messages", typeof(Messages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اضافة.
        /// </summary>
        internal static string add_ar {
            get {
                return ResourceManager.GetString("add_ar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to لم يتم إضافة السؤال بنجاح.
        /// </summary>
        internal static string add_ar_failure {
            get {
                return ResourceManager.GetString("add_ar_failure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تم إضافة السؤال بنجاح.
        /// </summary>
        internal static string add_ar_success {
            get {
                return ResourceManager.GetString("add_ar_success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add.
        /// </summary>
        internal static string add_en {
            get {
                return ResourceManager.GetString("add_en", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The question was not added successfully.
        /// </summary>
        internal static string add_en_failure {
            get {
                return ResourceManager.GetString("add_en_failure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The question was added successfully.
        /// </summary>
        internal static string add_en_success {
            get {
                return ResourceManager.GetString("add_en_success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اضافة.
        /// </summary>
        internal static string add_text_ar {
            get {
                return ResourceManager.GetString("add_text_ar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add.
        /// </summary>
        internal static string add_text_en {
            get {
                return ResourceManager.GetString("add_text_en", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اضافة سؤال.
        /// </summary>
        internal static string add_title_ar {
            get {
                return ResourceManager.GetString("add_title_ar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Question.
        /// </summary>
        internal static string add_title_en {
            get {
                return ResourceManager.GetString("add_title_en", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to حدث خطأ ما أثناء التنفيذ .. يرجى المحاولة مرة أخرى أو الاتصال بالمسؤول..
        /// </summary>
        internal static string code_failure_ar {
            get {
                return ResourceManager.GetString("code_failure_ar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Something wrong happend while executing.. please try again or contact an administrator..
        /// </summary>
        internal static string code_failure_en {
            get {
                return ResourceManager.GetString("code_failure_en", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  لم تتم مصادقة المستخدم الحالي..
        /// </summary>
        internal static string database_authentication_failure_ar {
            get {
                return ResourceManager.GetString("database_authentication_failure_ar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to the current user is not authenticated..
        /// </summary>
        internal static string database_authentication_failure_en {
            get {
                return ResourceManager.GetString("database_authentication_failure_en", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  تم رفض الاتصال بقاعدة البيانات..
        /// </summary>
        internal static string database_connection_denied_ar {
            get {
                return ResourceManager.GetString("database_connection_denied_ar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to the connection to the database was denied..
        /// </summary>
        internal static string database_connection_denied_en {
            get {
                return ResourceManager.GetString("database_connection_denied_en", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to فشل الاتصال بقاعدة البيانات..
        /// </summary>
        internal static string database_connection_failure_ar {
            get {
                return ResourceManager.GetString("database_connection_failure_ar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to the connection to the database failed..
        /// </summary>
        internal static string database_connection_failure_en {
            get {
                return ResourceManager.GetString("database_connection_failure_en", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to فشل قاعدة البيانات ، يرجى الاتصال بالمسؤول..
        /// </summary>
        internal static string database_failure_ar {
            get {
                return ResourceManager.GetString("database_failure_ar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Database failure, please contact administrator..
        /// </summary>
        internal static string database_failure_en {
            get {
                return ResourceManager.GetString("database_failure_en", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to حدث خطأ ، يرجى إعادة تشغيل التطبيق أو الاتصال بالمسؤول..
        /// </summary>
        internal static string default_message_ar {
            get {
                return ResourceManager.GetString("default_message_ar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error happened, please restart the application or contact an administrator..
        /// </summary>
        internal static string default_message_en {
            get {
                return ResourceManager.GetString("default_message_en", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to هناك حقول فارغة ، يرجى تعبئتها.
        /// </summary>
        internal static string empty_fields_ar {
            get {
                return ResourceManager.GetString("empty_fields_ar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There are empty fields, please fill them.
        /// </summary>
        internal static string empty_fields_en {
            get {
                return ResourceManager.GetString("empty_fields_en", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to خروج.
        /// </summary>
        internal static string exit_ar {
            get {
                return ResourceManager.GetString("exit_ar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to هل أنت متأكد من انك تريد الخروج؟.
        /// </summary>
        internal static string exit_ar_text {
            get {
                return ResourceManager.GetString("exit_ar_text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exit.
        /// </summary>
        internal static string exit_en {
            get {
                return ResourceManager.GetString("exit_en", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to exit?.
        /// </summary>
        internal static string exit_en_text {
            get {
                return ResourceManager.GetString("exit_en_text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تحميل التطبيق.
        /// </summary>
        internal static string form_loading_ar {
            get {
                return ResourceManager.GetString("form_loading_ar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to حدث خطأ ما أثناء تحميل التطبيق.
        /// </summary>
        internal static string form_loading_ar_failure {
            get {
                return ResourceManager.GetString("form_loading_ar_failure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Application loading.
        /// </summary>
        internal static string form_loading_en {
            get {
                return ResourceManager.GetString("form_loading_en", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Something wrong happend while loading the application.
        /// </summary>
        internal static string form_loading_en_failure {
            get {
                return ResourceManager.GetString("form_loading_en_failure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to لغة.
        /// </summary>
        internal static string language_ar {
            get {
                return ResourceManager.GetString("language_ar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تم تغيير اللغة بنجاح ، سيتم إعادة تشغيل التطبيق ليعكس التغييرات الجديدة ...
        /// </summary>
        internal static string language_ar_text {
            get {
                return ResourceManager.GetString("language_ar_text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language.
        /// </summary>
        internal static string language_en {
            get {
                return ResourceManager.GetString("language_en", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The language was changed successfully, the application will restart to reflect the new changes...
        /// </summary>
        internal static string language_en_text {
            get {
                return ResourceManager.GetString("language_en_text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to فشل التحديث ، لا يوجد شيء لتحديثه..
        /// </summary>
        internal static string nothing_to_update_ar {
            get {
                return ResourceManager.GetString("nothing_to_update_ar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update failed, there is nothing to update..
        /// </summary>
        internal static string nothing_to_update_en {
            get {
                return ResourceManager.GetString("nothing_to_update_en", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الترتيب.
        /// </summary>
        internal static string Order_ar {
            get {
                return ResourceManager.GetString("Order_ar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Order.
        /// </summary>
        internal static string Order_en {
            get {
                return ResourceManager.GetString("Order_en", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to حدث خطأ ما ، السؤال الحالي إما تم حذفه أو تحديثه ، يرجى التحديث والمحاولة مرة أخرى..
        /// </summary>
        internal static string question_out_of_date_ar {
            get {
                return ResourceManager.GetString("question_out_of_date_ar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Something wrong happened, the current question is either deleted or updated, please refresh and try again..
        /// </summary>
        internal static string question_out_of_date_en {
            get {
                return ResourceManager.GetString("question_out_of_date_en", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ازالة.
        /// </summary>
        internal static string remove_ar {
            get {
                return ResourceManager.GetString("remove_ar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to هل أنت متأكد أنك تريد حذف السؤال المحدد؟ لا يمكن استرداد الأسئلة التي تمت إزالتها..
        /// </summary>
        internal static string remove_ar_confirmation {
            get {
                return ResourceManager.GetString("remove_ar_confirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to لم تتم إزالة السؤال.
        /// </summary>
        internal static string remove_ar_failure {
            get {
                return ResourceManager.GetString("remove_ar_failure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تمت إزالة السؤال بنجاح.
        /// </summary>
        internal static string remove_ar_success {
            get {
                return ResourceManager.GetString("remove_ar_success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove.
        /// </summary>
        internal static string remove_en {
            get {
                return ResourceManager.GetString("remove_en", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to delete the selected question? removed questions cann&apos;t be recoverd..
        /// </summary>
        internal static string remove_en_confirmation {
            get {
                return ResourceManager.GetString("remove_en_confirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The question was not removed.
        /// </summary>
        internal static string remove_en_failure {
            get {
                return ResourceManager.GetString("remove_en_failure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The question was removed successfully.
        /// </summary>
        internal static string remove_en_success {
            get {
                return ResourceManager.GetString("remove_en_success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to فشل الاتصال بالخادم..
        /// </summary>
        internal static string server_connection_failure_ar {
            get {
                return ResourceManager.GetString("server_connection_failure_ar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  the connection to the server failed..
        /// </summary>
        internal static string server_connection_failure_en {
            get {
                return ResourceManager.GetString("server_connection_failure_en", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to إما أن الخادم معطل أو أنه غير موجود..
        /// </summary>
        internal static string server_not_found_or_down_ar {
            get {
                return ResourceManager.GetString("server_not_found_or_down_ar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to the server is either down or it doesn&apos;t exist..
        /// </summary>
        internal static string server_not_found_or_down_en {
            get {
                return ResourceManager.GetString("server_not_found_or_down_en", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الخادم متوقف مؤقتًا حاليًا..
        /// </summary>
        internal static string server_paused_ar {
            get {
                return ResourceManager.GetString("server_paused_ar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to the server is currently paused..
        /// </summary>
        internal static string server_paused_en {
            get {
                return ResourceManager.GetString("server_paused_en", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to لم يتم حفظ الإعدادات ....
        /// </summary>
        internal static string settings_save_ar_failure {
            get {
                return ResourceManager.GetString("settings_save_ar_failure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تم حفظ الإعدادات بنجاح.
        /// </summary>
        internal static string settings_save_ar_success {
            get {
                return ResourceManager.GetString("settings_save_ar_success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The settings were not saved....
        /// </summary>
        internal static string settings_save_en_failure {
            get {
                return ResourceManager.GetString("settings_save_en_failure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The settings were successfuly saved.
        /// </summary>
        internal static string settings_save_en_success {
            get {
                return ResourceManager.GetString("settings_save_en_success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to منزلق.
        /// </summary>
        internal static string Slider_ar {
            get {
                return ResourceManager.GetString("Slider_ar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Slider.
        /// </summary>
        internal static string Slider_en {
            get {
                return ResourceManager.GetString("Slider_en", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مبتسم.
        /// </summary>
        internal static string Smiley_ar {
            get {
                return ResourceManager.GetString("Smiley_ar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Smiley.
        /// </summary>
        internal static string Smiley_en {
            get {
                return ResourceManager.GetString("Smiley_en", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to خطأ دقيق: -.
        /// </summary>
        internal static string specific_error_ar {
            get {
                return ResourceManager.GetString("specific_error_ar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exact error :-.
        /// </summary>
        internal static string specific_error_en {
            get {
                return ResourceManager.GetString("specific_error_en", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نجمة.
        /// </summary>
        internal static string Star_ar {
            get {
                return ResourceManager.GetString("Star_ar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Star.
        /// </summary>
        internal static string Star_en {
            get {
                return ResourceManager.GetString("Star_en", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ناجح..
        /// </summary>
        internal static string success_ar {
            get {
                return ResourceManager.GetString("success_ar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Successful..
        /// </summary>
        internal static string success_en {
            get {
                return ResourceManager.GetString("success_en", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اختبار الاتصال.
        /// </summary>
        internal static string test_ar {
            get {
                return ResourceManager.GetString("test_ar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to لم يكن الاتصال بقاعدة البيانات ناجحًا.
        /// </summary>
        internal static string test_ar_failure {
            get {
                return ResourceManager.GetString("test_ar_failure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تم الاتصال بقاعدة البيانات بنجاح.
        /// </summary>
        internal static string test_ar_success {
            get {
                return ResourceManager.GetString("test_ar_success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Test Connection.
        /// </summary>
        internal static string test_en {
            get {
                return ResourceManager.GetString("test_en", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The connection to the database wasn&apos;t successful.
        /// </summary>
        internal static string test_en_failure {
            get {
                return ResourceManager.GetString("test_en_failure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The connection to the database was successful.
        /// </summary>
        internal static string test_en_success {
            get {
                return ResourceManager.GetString("test_en_success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to النص.
        /// </summary>
        internal static string Text_ar {
            get {
                return ResourceManager.GetString("Text_ar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Text.
        /// </summary>
        internal static string Text_en {
            get {
                return ResourceManager.GetString("Text_en", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to النوع.
        /// </summary>
        internal static string Type_ar {
            get {
                return ResourceManager.GetString("Type_ar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type.
        /// </summary>
        internal static string Type_en {
            get {
                return ResourceManager.GetString("Type_en", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تحديث.
        /// </summary>
        internal static string update_ar {
            get {
                return ResourceManager.GetString("update_ar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to لم يتم تحديث السؤال بنجاح.
        /// </summary>
        internal static string update_ar_failure {
            get {
                return ResourceManager.GetString("update_ar_failure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تم تحديث السؤال بنجاح.
        /// </summary>
        internal static string update_ar_success {
            get {
                return ResourceManager.GetString("update_ar_success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update.
        /// </summary>
        internal static string update_en {
            get {
                return ResourceManager.GetString("update_en", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The question was not updated successfully.
        /// </summary>
        internal static string update_en_failure {
            get {
                return ResourceManager.GetString("update_en_failure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The question was updated successfully.
        /// </summary>
        internal static string update_en_success {
            get {
                return ResourceManager.GetString("update_en_success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تحديث.
        /// </summary>
        internal static string update_text_ar {
            get {
                return ResourceManager.GetString("update_text_ar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update.
        /// </summary>
        internal static string update_text_en {
            get {
                return ResourceManager.GetString("update_text_en", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تحديث سؤال.
        /// </summary>
        internal static string update_title_ar {
            get {
                return ResourceManager.GetString("update_title_ar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update Question.
        /// </summary>
        internal static string update_title_en {
            get {
                return ResourceManager.GetString("update_title_en", resourceCulture);
            }
        }
    }
}
